### ISSUE TITLE
Outdated dependency marked@0.3.3

### ISSUE THREAD

**Issue by alexindigo** [eGavr/toc-md#14]
Re: https://nodesecurity.io/advisories/marked_redos

**Comment by eGavr** [comment]
Can you make a pull request ?

**Comment by alexindigo** [comment]
Done: https://github.com/eGavr/toc-md/pull/15

**Comment by eGavr** [comment]
I've [commented](https://github.com/eGavr/toc-md/pull/15#issuecomment-198888934) in a PR why I can not update this dependency.
