### ISSUE TITLE
Doesn't respect existing anchors

### ISSUE THREAD

**Issue by alexindigo** [eGavr/toc-md#16]
I have part of the readme generated by [jsdoc-to-markdown](https://www.npmjs.com/package/jsdoc-to-markdown) and it creates it's own anchors for each function, like this:

```
<a name="Footprint+activate"></a>

#### footprint.activate() ⇒ <code>void</code>
```

Although `toc-md` detects it as a header and adds it to the list,
it refers to different anchors (that don't exist on the page).

```
    - [footprint.activate() ⇒ <code>void</code>](#footprintactivate--codevoidcode)
```

Would nice to recognize existing markers to use them for the reference.

Thank you.

**Comment by eGavr** [comment]
Hi! It is a bug!

The header

`#### footprint.activate() ⇒ <code>void</code>`

should be displayed is a TOC as

` - [footprint.activate() ⇒ <code>void</code>](#footprintactivate--void)`

-------

> Although toc-md detects it as a header and adds it to the list...

If you do not want to display a header in a TOC you can ignore it, see the [docs](https://github.com/eGavr/toc-md#ignoring-of-headers).

**Comment by eGavr** [comment]
A little bit more detail description can be found in another [comment](https://github.com/eGavr/toc-md/pull/17#issuecomment-198794987).

**Comment by alexindigo** [comment]
*(Copying it over)*

Let's focus on one of the headers that ends up in the TOC, for example this one:

```
<a name="Footprint+transport"></a>

#### footprint.transport ⇒ <code>void</code>
```

after I run `toc-md` I get following reference to this header at the top of my file:

```
- [footprint.transport ⇒ <code>void</code>](#footprinttransport--codevoidcode)
```

As you can see it references `#footprinttransport--codevoidcode` anchor, assuming that Github and NPM would generate it while rendering markdown into HTML.

But there is another anchor already present on the page for this header – `name="Footprint+transport"`,
so it would be nice if `toc-md` could recognize it and use it instead of auto-generated one.

So TOC would look like following:

```
- [footprint.transport ⇒ <code>void</code>](#Footprint+transport)
```

PS. Also, this is internal project and we're using Stash, not Github, so `md->html` rendering is a bit different.

I hope it helped. 

Thank you.
